name: Translate

on:
  push:
    branches: [ "*" ]
    paths:
      - src/en-us/**
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    env:
      DIFY_API_KEY: ${{ secrets.DIFY_API_KEY }}
      LANGUAGES: 'zh-hk fr' # Add languages here

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3 python3-pip
        pip3 install requests

    - name: Get changed files in src/en-us since last push
      id: get_changes
      run: |
        git fetch origin main
        CHANGED_FILES=$(git diff --name-only origin/main -- src/en-us/)
        
        FIXED_CHANGED_FILES=$(echo "$CHANGED_FILES" | tr '\n' '~' | sed 's/ /_/g')
    
        echo "Changed files in src/en-us since last push:"
        echo "$FIXED_CHANGED_FILES"
        echo "changed_files=$FIXED_CHANGED_FILES" >> $GITHUB_ENV

    - name: Process each changed file
      if: env.changed_files != ''
      run: |
        git config --global advice.detachedHead false
        IFS='~'
        changed_files="${{ env.changed_files }}"
    
        for file in $changed_files; do
          file="${file//_/ }"
          echo "Currently translating: $file"
          base_path=$(dirname "$file")
          base_name=$(basename "$file")
          eng_content="${file}"
    
          IFS=' '
          for lang in $LANGUAGES; do
            translation_file_content="${base_path/en-us/$lang}/${base_name}"
            echo "Processing translation for: $lang"
            ls -al
            python3 .github/workflows/scripts/dify_translation.py "$eng_content" "$translation_file_content" "$lang"
          done
        done

    - name: Check and create translation files
      run: |
        EN_FILES=$(find src/en-us -type f)
        
        for file in $EN_FILES; do
          echo "Checking translations for: \"$file\""
          base_name=$(basename "$file")
          base_path=$(dirname "$file")
          
          IFS=' ' read -r -a languages <<< "${{ env.LANGUAGES }}"
          for lang in "${languages[@]}"; do
            translation_file="${base_path/en-us/$lang}/$base_name"
    
            if [ ! -f "$translation_file" ]; then
              echo "Translation file does not exist: \"$translation_file\""
              echo "Creating translation file using Dify API for: $lang"
              
              python3 .github/workflows/scripts/dify_translation.py "$eng_content" "$translation_file_content" "$lang"
            else
              echo "Translation file already exists: \"$translation_file\""
            fi
          done
        done
